namespace GossipCheck.DAO.Entities
{
    public enum BiasRating
    {
        NA,
        Conspiracy,
        ConspiracyAndPseudoscience,
        ConspiracyPseudoscience,
        ExtremeLeft,
        ExtremeRight,
        ExtremeRightPropagandaConspiracyAntiIslam,
        ExtremeRightPropagandaConspiracyFakeNews,
        ExtremeRightPropagandaSomeFakeNews,
        FarLeft,
        FarLeftBias,
        FarRight,
        FarRightConspiracyPseusdoscience,
        JunkNews,
        LeastBiased,
        LeastProScience,
        Left,
        LeftBiased,
        LeftCenter,
        LeftPseudoscience,
        NotRated,
        ProScience,
        Pseudoscience,
        Right,
        RightCenter,
        RightConspiracy,
        RightConspiracyAndPseudoscience,
        RightConspiracyPseudoscience,
        RightPseudoscience,
        RightSatire,
        Satire
    }
}