version: "3.9"
services:

  webscraper: 
    image: gossipcheck.azurecr.io/webscraper
    container_name: webscraper
    environment:
      ScraperServiceConfig__ApiKey: ${SCRAPER_SERVICE_APIKEY}
      NLUServiceConfig__ApiKey: ${NLU_SERVICE_APIKEY}
    ports:
      - "5001:80"

  ai: 
    image: gossipcheck.azurecr.io/stance-detection-ai
    container_name: stance-detection-ai
    ports:
      - "5002:5000"

  webapi: 
    image: gossipcheck.azurecr.io/webapi
    container_name: webapi
    environment:
      StanceDetector__WebScraperUrl: http://localhost:5001,
      StanceDetector__StanceDetectionAiUrl: http://localhost:5002
      ConnectionStrings__DBconnection: ${DB_CONNECTION}
    ports:
      - "5003:80"
