version: "3.9"
services:

  webscraper: 
    image: ${CONTAINER_REGISTRY}/webscraper
    container_name: webscraper
    environment:
      ScraperServiceConfig__ApiKey: ${SCRAPER_SERVICE_APIKEY}
      NLUServiceConfig__ApiKey: ${NLU_SERVICE_APIKEY}
    ports:
      - "5001:80"

  ai: 
    image: ${CONTAINER_REGISTRY}/stance-detection-ai
    container_name: stance-detection-ai
    ports:
      - "5002:5000"

  webapi: 
    image: ${CONTAINER_REGISTRY}/webapi
    container_name: webapi
    environment:
      StanceDetector__WebScraperUrl: http://host.docker.internal:5001
      StanceDetector__StanceDetectionAiUrl: http://host.docker.internal:5002
      ConnectionStrings__DBconnection: ${DB_CONNECTION}
    ports:
      - "5003:80"

  mssql-server:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql-server
    volumes:
      - mssql-server-data:/var/opt/mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${SQLSERVER_SA_PASSWORD}
    ports:
      - "1433:1433"


volumes:
  mssql-server-data: