using System.Collections.Generic;

namespace GossipCheck.BLL.Models
{
    internal static class LanguageCodes
    {
        public static Dictionary<Language, string> Codes = new Dictionary<Language, string>()
        {
            { Language.Afrikaans, "af" },
            { Language.Arabic, "ar" },
            { Language.Bulgarian, "bg" },
            { Language.Bengali, "bn" },
            { Language.Catalan, "ca" },
            { Language.Valencian, "ca" },
            { Language.Chinese, "cn" },
            { Language.Czech, "cs" },
            { Language.Welsh, "cy" },
            { Language.Danish, "da" },
            { Language.German, "de" },
            { Language.Greek, "el" },
            { Language.English, "en" },
            { Language.Spanish, "es" },
            { Language.Castilian, "es" },
            { Language.Estonian, "et" },
            { Language.Persian, "fa" },
            { Language.Finnish, "fi" },
            { Language.French, "fr" },
            { Language.Gujarati, "gu" },
            { Language.Hebrew, "he" },
            { Language.Hindi, "hi" },
            { Language.Croatian, "hr" },
            { Language.Hungarian, "hu" },
            { Language.Indonesian, "id" },
            { Language.Italian, "it" },
            { Language.Japanese, "ja" },
            { Language.Kannada, "kn" },
            { Language.Korean, "ko" },
            { Language.Lithuanian, "lt" },
            { Language.Latvian, "lv" },
            { Language.Macedonian, "mk" },
            { Language.Malayalam, "ml" },
            { Language.Marathi, "mr" },
            { Language.Nepali, "ne" },
            { Language.Dutch, "nl" },
            { Language.Flemish, "nl" },
            { Language.Norwegian, "no" },
            { Language.Punjabi, "pa" },
            { Language.Panjabi, "pa" },
            { Language.Polish, "pl" },
            { Language.Portuguese, "pt" },
            { Language.Moldovan, "ro" },
            { Language.Moldavian, "ro" },
            { Language.Romanian, "ro" },
            { Language.Russian, "ru" },
            { Language.Slovak, "sk" },
            { Language.Slovenian, "sl" },
            { Language.Somali, "so" },
            { Language.Albanian, "sq" },
            { Language.Swedish, "sv" },
            { Language.Swahili, "sw" },
            { Language.Tamil, "ta" },
            { Language.Telugu, "te" },
            { Language.Thai, "th" },
            { Language.Tagalog, "tl" },
            { Language.Turkish, "tr" },
            { Language.Twi, "tw" },
            { Language.Ukrainian, "uk" },
            { Language.Urdu, "ur" },
            { Language.Vietnamese, "vi" }
        };
    }
}
