let response = `
{
  "verdict": "MostLikelyTrue",
  "relatedArticles": [
      {
          "articleUrl": "https://www.irishtimes.com/news/world/peru-election-on-knife-edge-as-leftist-castillo-closes-fujimori-s-lead-1.4586805",
          "stance": "Agree",
          "factuality": "High",
          "bias": "NA",
          "mediaType": "NA",
          "popularity": "NA",
          "mbfcCredibilityRating": "NA",
          "reasoning": null,
          "country": "Ireland",
          "worldPressFreedomRank": null,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/the-irish-times/"
      },
      {
          "articleUrl": "https://www.irishtimes.com/news/world/peruvians-head-to-polls-in-election-divided-by-class-and-geography-1.4585761",
          "stance": "Agree",
          "factuality": "High",
          "bias": "NA",
          "mediaType": "NA",
          "popularity": "NA",
          "mbfcCredibilityRating": "NA",
          "reasoning": null,
          "country": "Ireland",
          "worldPressFreedomRank": null,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/the-irish-times/"
      },
      {
          "articleUrl": "https://www.irishtimes.com/news/world/peru-election-on-knife-edge-as-leftist-castillo-closes-fujimori-s-lead-1.4586805",
          "stance": "Agree",
          "factuality": "High",
          "bias": "NA",
          "mediaType": "NA",
          "popularity": "NA",
          "mbfcCredibilityRating": "NA",
          "reasoning": null,
          "country": "Ireland",
          "worldPressFreedomRank": null,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/the-irish-times/"
      },
      {
          "articleUrl": "https://www.irishtimes.com/news/world/peruvians-head-to-polls-in-election-divided-by-class-and-geography-1.4585761",
          "stance": "Agree",
          "factuality": "High",
          "bias": "NA",
          "mediaType": "NA",
          "popularity": "NA",
          "mbfcCredibilityRating": "NA",
          "reasoning": null,
          "country": "Ireland",
          "worldPressFreedomRank": null,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/the-irish-times/"
      },
      {
          "articleUrl": "https://www.metro.us/peruvians-vote-to-elect/",
          "stance": "Agree",
          "factuality": "High",
          "bias": "LeftCenter",
          "mediaType": "Newspaper",
          "popularity": "MinimalTraffic",
          "mbfcCredibilityRating": "HighCredibility",
          "reasoning": null,
          "country": "USA",
          "worldPressFreedomRank": 45,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/metro/"
      },
      {
          "articleUrl": "https://www.reuters.com/world/americas/peru-awakes-uncertain-future-with-polarized-vote-knife-edge-2021-06-07/",
          "stance": "Agree",
          "factuality": "VeryHigh",
          "bias": "LeastBiased",
          "mediaType": "NewsAgency",
          "popularity": "HighTraffic",
          "mbfcCredibilityRating": "HighCredibility",
          "reasoning": null,
          "country": "United Kingdom",
          "worldPressFreedomRank": 35,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/reuters/"
      },
      {
          "articleUrl": "https://www.sbs.com.au/news/divided-by-class-and-geography-peruvians-head-to-the-polls-to-elect-a-president",
          "stance": "Agree",
          "factuality": "High",
          "bias": "NA",
          "mediaType": "NA",
          "popularity": "NA",
          "mbfcCredibilityRating": "NA",
          "reasoning": null,
          "country": "Australia",
          "worldPressFreedomRank": null,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/special-broadcasting-service-sbs/"
      },
      {
          "articleUrl": "https://www.sfgate.com/news/article/Peruvian-voters-face-choice-between-2-polarizing-16228038.php",
          "stance": "Discuss",
          "factuality": "High",
          "bias": "LeftCenter",
          "mediaType": "Website",
          "popularity": "HighTraffic",
          "mbfcCredibilityRating": "HighCredibility",
          "reasoning": null,
          "country": "USA",
          "worldPressFreedomRank": 44,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/sfgate/"
      },
      {
          "articleUrl": "https://www.sfgate.com/news/article/Peruvians-to-pick-new-president-amid-relentless-16221891.php",
          "stance": "Discuss",
          "factuality": "High",
          "bias": "LeftCenter",
          "mediaType": "Website",
          "popularity": "HighTraffic",
          "mbfcCredibilityRating": "HighCredibility",
          "reasoning": null,
          "country": "USA",
          "worldPressFreedomRank": 44,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/sfgate/"
      },
      {
          "articleUrl": "https://www.independent.co.uk/news/world/americas/us-politics/peruvians-to-pick-new-president-amid-relentless-pandemic-congress-lima-hugo-chavez-polls-united-states-b1859033.html",
          "stance": "Unrelated",
          "factuality": "Mixed",
          "bias": "LeftCenter",
          "mediaType": "Newspaper",
          "popularity": "HighTraffic",
          "mbfcCredibilityRating": "MediumCredibility",
          "reasoning": null,
          "country": "United Kingdom",
          "worldPressFreedomRank": 35,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/the-independent/"
      },
      {
          "articleUrl": "https://indianexpress.com/article/world/peruvians-head-to-polls-in-polarizing-run-off-7346839/",
          "stance": "Unrelated",
          "factuality": "NA",
          "bias": "NA",
          "mediaType": "NA",
          "popularity": "NA",
          "mbfcCredibilityRating": "NA",
          "reasoning": null,
          "country": "",
          "worldPressFreedomRank": null,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/sources-pending/"
      },
      {
          "articleUrl": "https://news.yahoo.com/peru-election-country-edge-ahead-234338060.html",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "LeftCenter",
          "mediaType": "Website",
          "popularity": "HighTraffic",
          "mbfcCredibilityRating": "HighCredibility",
          "reasoning": null,
          "country": "USA",
          "worldPressFreedomRank": 45,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/yahoo-news/"
      },
      {
          "articleUrl": "https://www.bbc.co.uk/news/world-latin-america-57341541",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "LeftCenter",
          "mediaType": "TvStation",
          "popularity": "HighTraffic",
          "mbfcCredibilityRating": "HighCredibility",
          "reasoning": null,
          "country": "United Kingdom",
          "worldPressFreedomRank": 35,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/bbc/"
      },
      {
          "articleUrl": "https://www.bbc.co.uk/news/world-latin-america-57381362",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "LeftCenter",
          "mediaType": "TvStation",
          "popularity": "HighTraffic",
          "mbfcCredibilityRating": "HighCredibility",
          "reasoning": null,
          "country": "United Kingdom",
          "worldPressFreedomRank": 35,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/bbc/"
      },
      {
          "articleUrl": "https://www.bbc.co.uk/news/world-latin-america-57341541",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "LeftCenter",
          "mediaType": "TvStation",
          "popularity": "HighTraffic",
          "mbfcCredibilityRating": "HighCredibility",
          "reasoning": null,
          "country": "United Kingdom",
          "worldPressFreedomRank": 35,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/bbc/"
      },
      {
          "articleUrl": "https://www.bbc.co.uk/news/world-latin-america-57381362",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "LeftCenter",
          "mediaType": "TvStation",
          "popularity": "HighTraffic",
          "mbfcCredibilityRating": "HighCredibility",
          "reasoning": null,
          "country": "United Kingdom",
          "worldPressFreedomRank": 35,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/bbc/"
      },
      {
          "articleUrl": "https://www.bbc.com/news/world-latin-america-57341541",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "LeftCenter",
          "mediaType": "TvStation",
          "popularity": "HighTraffic",
          "mbfcCredibilityRating": "HighCredibility",
          "reasoning": null,
          "country": "United Kingdom",
          "worldPressFreedomRank": 35,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/bbc/"
      },
      {
          "articleUrl": "https://www.bbc.com/news/world-latin-america-57381362",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "LeftCenter",
          "mediaType": "TvStation",
          "popularity": "HighTraffic",
          "mbfcCredibilityRating": "HighCredibility",
          "reasoning": null,
          "country": "United Kingdom",
          "worldPressFreedomRank": 35,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/bbc/"
      },
      {
          "articleUrl": "https://www.bbc.com/news/world-latin-america-57341541",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "LeftCenter",
          "mediaType": "TvStation",
          "popularity": "HighTraffic",
          "mbfcCredibilityRating": "HighCredibility",
          "reasoning": null,
          "country": "United Kingdom",
          "worldPressFreedomRank": 35,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/bbc/"
      },
      {
          "articleUrl": "https://www.bbc.com/news/world-latin-america-57381362",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "LeftCenter",
          "mediaType": "TvStation",
          "popularity": "HighTraffic",
          "mbfcCredibilityRating": "HighCredibility",
          "reasoning": null,
          "country": "United Kingdom",
          "worldPressFreedomRank": 35,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/bbc/"
      },
      {
          "articleUrl": "https://www.csmonitor.com/World/Americas/2021/0604/In-polarizing-election-Peru-hears-echoes-of-the-past",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "LeastBiased",
          "mediaType": "Magazine",
          "popularity": "MediumTraffic",
          "mbfcCredibilityRating": "HighCredibility",
          "reasoning": null,
          "country": "USA",
          "worldPressFreedomRank": 45,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/christian-science-monitor/"
      },
      {
          "articleUrl": "https://www.dailyherald.com/article/20210603/news/306039950",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "NA",
          "mediaType": "NA",
          "popularity": "NA",
          "mbfcCredibilityRating": "NA",
          "reasoning": null,
          "country": "USA",
          "worldPressFreedomRank": null,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/daily-herald/"
      },
      {
          "articleUrl": "https://www.dailyherald.com/article/20210606/news/306069981",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "NA",
          "mediaType": "NA",
          "popularity": "NA",
          "mbfcCredibilityRating": "NA",
          "reasoning": null,
          "country": "USA",
          "worldPressFreedomRank": null,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/daily-herald/"
      },
      {
          "articleUrl": "https://www.dailyherald.com/article/20210603/news/306039950",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "NA",
          "mediaType": "NA",
          "popularity": "NA",
          "mbfcCredibilityRating": "NA",
          "reasoning": null,
          "country": "USA",
          "worldPressFreedomRank": null,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/daily-herald/"
      },
      {
          "articleUrl": "https://www.dailyherald.com/article/20210606/news/306069981",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "NA",
          "mediaType": "NA",
          "popularity": "NA",
          "mbfcCredibilityRating": "NA",
          "reasoning": null,
          "country": "USA",
          "worldPressFreedomRank": null,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/daily-herald/"
      },
      {
          "articleUrl": "https://www.darientimes.com/news/article/Peruvian-voters-face-choice-between-2-polarizing-16228038.php",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "NA",
          "mediaType": "NA",
          "popularity": "NA",
          "mbfcCredibilityRating": "NA",
          "reasoning": null,
          "country": "USA",
          "worldPressFreedomRank": null,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/darien-times/"
      },
      {
          "articleUrl": "https://www.darientimes.com/news/article/Peruvians-to-pick-new-president-amid-relentless-16221891.php",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "NA",
          "mediaType": "NA",
          "popularity": "NA",
          "mbfcCredibilityRating": "NA",
          "reasoning": null,
          "country": "USA",
          "worldPressFreedomRank": null,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/darien-times/"
      },
      {
          "articleUrl": "https://www.darientimes.com/news/article/Peruvian-voters-face-choice-between-2-polarizing-16228038.php",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "NA",
          "mediaType": "NA",
          "popularity": "NA",
          "mbfcCredibilityRating": "NA",
          "reasoning": null,
          "country": "USA",
          "worldPressFreedomRank": null,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/darien-times/"
      },
      {
          "articleUrl": "https://www.darientimes.com/news/article/Peruvians-to-pick-new-president-amid-relentless-16221891.php",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "NA",
          "mediaType": "NA",
          "popularity": "NA",
          "mbfcCredibilityRating": "NA",
          "reasoning": null,
          "country": "USA",
          "worldPressFreedomRank": null,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/darien-times/"
      },
      {
          "articleUrl": "https://www.nhregister.com/news/article/Peruvian-voters-face-choice-between-2-polarizing-16228038.php",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "NA",
          "mediaType": "NA",
          "popularity": "NA",
          "mbfcCredibilityRating": "NA",
          "reasoning": null,
          "country": "USA",
          "worldPressFreedomRank": null,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/new-haven-register/"
      },
      {
          "articleUrl": "https://www.ny1.com/nyc/all-boroughs/ap-top-news/2021/06/06/peruvian-voters-face-choice-between-2-polarizing-populists",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "NA",
          "mediaType": "NA",
          "popularity": "NA",
          "mbfcCredibilityRating": "NA",
          "reasoning": null,
          "country": "USA",
          "worldPressFreedomRank": null,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/spectrum-news-ny1/"
      },
      {
          "articleUrl": "https://www.seattlepi.com/news/article/Peruvian-voters-face-choice-between-2-polarizing-16228038.php",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "NA",
          "mediaType": "NA",
          "popularity": "NA",
          "mbfcCredibilityRating": "NA",
          "reasoning": null,
          "country": "USA",
          "worldPressFreedomRank": null,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/seattle-post-intelligencer/"
      },
      {
          "articleUrl": "https://www.seattlepi.com/news/article/Peruvians-to-pick-new-president-amid-relentless-16221891.php",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "NA",
          "mediaType": "NA",
          "popularity": "NA",
          "mbfcCredibilityRating": "NA",
          "reasoning": null,
          "country": "USA",
          "worldPressFreedomRank": null,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/seattle-post-intelligencer/"
      },
      {
          "articleUrl": "https://www.seattlepi.com/news/article/Peruvian-voters-face-choice-between-2-polarizing-16228038.php",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "NA",
          "mediaType": "NA",
          "popularity": "NA",
          "mbfcCredibilityRating": "NA",
          "reasoning": null,
          "country": "USA",
          "worldPressFreedomRank": null,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/seattle-post-intelligencer/"
      },
      {
          "articleUrl": "https://www.seattlepi.com/news/article/Peruvians-to-pick-new-president-amid-relentless-16221891.php",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "NA",
          "mediaType": "NA",
          "popularity": "NA",
          "mbfcCredibilityRating": "NA",
          "reasoning": null,
          "country": "USA",
          "worldPressFreedomRank": null,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/seattle-post-intelligencer/"
      },
      {
          "articleUrl": "https://www.sfgate.com/news/article/Peruvian-voters-face-choice-between-2-polarizing-16228038.php",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "LeftCenter",
          "mediaType": "Website",
          "popularity": "HighTraffic",
          "mbfcCredibilityRating": "HighCredibility",
          "reasoning": null,
          "country": "USA",
          "worldPressFreedomRank": 44,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/sfgate/"
      },
      {
          "articleUrl": "https://www.sfgate.com/news/article/Peruvians-to-pick-new-president-amid-relentless-16221891.php",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "LeftCenter",
          "mediaType": "Website",
          "popularity": "HighTraffic",
          "mbfcCredibilityRating": "HighCredibility",
          "reasoning": null,
          "country": "USA",
          "worldPressFreedomRank": 44,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/sfgate/"
      },
      {
          "articleUrl": "https://www.startribune.com/peruvians-to-pick-new-president-amid-relentless-pandemic/600064155/",
          "stance": "Unrelated",
          "factuality": "High",
          "bias": "NA",
          "mediaType": "NA",
          "popularity": "NA",
          "mbfcCredibilityRating": "NA",
          "reasoning": null,
          "country": "USA",
          "worldPressFreedomRank": null,
          "mbfcPageUrl": "https://mediabiasfactcheck.com/minneapolis-star-tribune/"
      }
  ]
}`

response = JSON.parse(response);
export { response }